// This file is no longer used. Enums have been moved to individual files:
// - BaseStatus.cs
// - PriorityLevel.cs
// - EnvironmentType.cs
// - LogLevel.cs
// - NotificationType.cs
// - AccessLevel.cs
// - ThemeMode.cs
// - DataFormat.cs
// - SortOrder.cs
// - FileType.cs
// - ConnectionStatus.cs
// - UsStates.cs
// - CurrencyType.cs
// - WeekDays.cs
// - MonthOfYear.cs
// - Gender.cs
// - MeasurementUnit.cs
// - TimeZoneRegion.cs
// - PaymentStatus.cs
// - OrderStatus.cs
// - SubscriptionPlan.cs
// - AlertLevel.cs